# Generated by Django 5.2.5 on 2025-11-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN-10 or ISBN-13 (stored normalized without hyphens/spaces)', max_length=13, null=True, unique=True),
        ),
    ]
