# Generated by Django 5.2.5 on 2025-11-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookshelfitem",
            name="tag",
            field=models.IntegerField(default=0),
        ),
    ]
