# Generated by Django 5.2.7 on 2025-11-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0002_bookshelfitem_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelfitem',
            name='tag',
            field=models.CharField(choices=[('0', 'Untagged'), ('1', 'Wanted'), ('2', 'Reading'), ('3', 'Read')], default='0', max_length=1),
        ),
    ]
